---
- name: jeffhibberd.com DNS records
  hosts: localhost
  gather_facts: no
  vars:
    login_info: &login_info
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"

  tasks:
    - name: create a managed zone
      gcp_dns_managed_zone:
        <<: *login_info
        name: jeffhibberddotcom
        dns_name: jeffhibberd.com.
        description: jeffhibberd.com managed zone
        state: present
      register: managed_zone

    - name: debug managed_zone var
      debug:
        var: managed_zone
        verbosity: 1

    - name: create MX records
      gcp_dns_resource_record_set:
        <<: *login_info
        name: "{{ managed_zone.dnsName }}"
        managed_zone: "{{ managed_zone }}"
        type: MX
        ttl: 14400
        target:
          - 1 ASPMX.L.GOOGLE.COM.
          - 5 ALT1.ASPMX.L.GOOGLE.COM.
          - 5 ALT2.ASPMX.L.GOOGLE.com.
          - 10 ASPMX2.GOOGLEMAIL.com.
          - 10 ASPMX3.GOOGLEMAIL.com.
